# Site settings

author: 小涛
email: telltao@qq.com
twitter_username: telltao
github_username:  telltao
googleplus_username: telltao

head-title: 欢迎访问我的网站
title: 欢迎你
#website
baseurl: ""
url: ""

#localhost
#baseurl: "/materialize-jekyll"
#url: "/materialize-jekyll"

# footer
description: <a class="red-text text-accent-1" href="https://beian.miit.gov.cn">工业和信息化部冀ICP备17021581号-1</a>

favo: "春梦随云散，飞花逐水流"
descrpt: "“巧者劳而智者忧，无能者无所求，饱食而遨游，泛若不系之舟”  ——《南华经》"


#
# Build settings
#

#exclude: [vendor]

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  hard_wrap: false
  highlight: true
  auto_ids:  true

sass:
  style: compressed

permalink: /posts/:categories/:title.html

paginate: 7
#paginate_path: 'page/:num'

gems: [jekyll-paginate, jekyll-last-modified-at, jemoji]


#
# Custom
#

# Color
# All css class, see: http://materializecss.com/color.html
header-color: "indigo lighten-1"
head-theme-color: "#5c6bc0"     # MUST in hex format, may the same as header-color. This color is for android chrome browser.

footer-color: "indigo lighten-1"
footer-button-color: "indigo lighten-2"
footer-link-color: "red-text text-accent-1"

share-button-color: "pink"
share-button-small-color: ""


##
#excerpt_separator: <!-- excerpt_end -->       # for post.excerpt